eka = input("Syötä kokonaisluku ")
toka = input("Syötä toinen kokonaisluku ")
ekaMuunnos = int(eka)
tokaMuunnos = int(toka)
print("Summa =", ekaMuunnos + tokaMuunnos)
print("Ero =", ekaMuunnos - tokaMuunnos)
print("Tulo =", ekaMuunnos * tokaMuunnos)